on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Build
        run: dotnet build --configuration Release
      - name: Hack around InternalName
        run: |
          cd DailyDuty/bin/x64/Release
          rm -rf DailyDuty/
          Get-ChildItem . | Where {$_.Name -match "DailyDuty"} | Rename-Item -NewName {$_.name -replace "DailyDuty","DailyDuty3" }
          Set-Content -Path DailyDuty3.json ((Get-Content DailyDuty3.json) -replace '"DailyDuty"', '"DailyDuty3"')
          cd ../../../..
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: DailyDuty/bin/x64/Release/*
